INSERT INTO DEPARTMENTS(DNAME, DCAPACITY)
VALUES('IT', 2), ('HR', 3), ('SALES', 4), ('ACCOUNTS', 1);


SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;

insert into employees(ename, esalary, departmentdid)
values('Nidhi R', 83738, 2);

select DNAME, DCAPACITY, ENAME, ESALARY
FROM DEPARTMENTS RIGHT JOIN EMPLOYEES
ON DEPARTMENTS.DID = EMPLOYEES.DEPARTMENTDID;